services:
  cvat_nginx:
    image: nginx:1.29.1-alpine3.22-slim
    container_name: cvat_nginx
    restart: always
    networks:
      cvat:
    ports:
      - 8088:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  cvat:
    name: cvat_nginx